version: '3.7'

networks:
  backend:
    driver: bridge 

services:

  hub:
    image: docker-selenium-grid/hub
    build:
      context: .
      dockerfile: ./hub/Dockerfile
      args:
        - TZ=UTC
    ports:
      - "4444:4444"
    networks:
      - backend

  node-chrome:
    image: docker-selenium-grid/node-chrome
    build:
      context: .
      dockerfile: ./node-chrome/Dockerfile
      args:
        - TZ=UTC
    environment:
        - HUB_HOST=hub
        - HUB_PORT=4444
    depends_on:
      - hub
    networks:
      - backend

  node-firefox:
    image: docker-selenium-grid/node-firefox
    build:
      context: .
      dockerfile: ./node-firefox/Dockerfile
      args:
        - TZ=UTC
    environment:
        - HUB_HOST=hub
        - HUB_PORT=4444
    depends_on:
      - hub
    networks:
      - backend
